whi_moveit_cpp_bridge:
  tf_prefix: "$(arg robot_name)"
  planning_group: jaka_zu5
  eef_link: Link_6
  tcp_pose_service: tcp_pose
  tcp_pose_topic: tcp_pose
  arm_state_topic: whi_arm_interface/arm_motion_state
