whi_moveit_cpp_bridge:
  ros__parameters:
    tf_prefix: ""
    planning_group: ur_manipulator
    link_index_map: {"shoulder_pan_joint": 0, "shoulder_lift_joint": 1, "elbow_joint": 2, "wrist_1_joint": 3, "wrist_2_joint": 4, "wrist_3_joint": 5}
    init_pose_groups: {"up": 0.1}
