whi_moveit_cpp_bridge:
  ros__parameters:
    tf_prefix: ""
    planning_group: jaka_a5
    eef_link: link_6
    arm_state_topic: whi_arm_interface/arm_motion_state
    init_pose_groups: {"home": 0.1}
