whi_moveit_cpp_bridge:
  tf_prefix: "$(arg robot_name)"
  planning_group: chin_crb7
  max_ik_try_count: 3
  tcp_pose_service: tcp_pose
  tcp_pose_topic: tcp_pose
  motion_state_topic: arm_motion_state
