whi_moveit_cpp_bridge:
  tf_prefix: "$(arg robot_name)"
  planning_group: manipulator
  max_ik_try_count: 30
  tcp_pose_service: tcp_pose
  tcp_pose_topic: tcp_pose
  arm_state_topic: /whi/ur_combined/whi_ur_robot_driver_bridge/arm_motion_state
